name: Test Python 🐍 package 📦
on: [push]
jobs:
  Build-and-Test:
    name: Build and test using Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools codecov pytest
          python3 setup.py develop

      - name: Run tests and create coverage report
        run : |
          coverage run -m unittest -v

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
